(defun exec-move-com (game args)
  (when (< (length args) 2)
    (princ "The Move command requires 2 numbers as args")
    (return-from exec-move-com nil))
  (let ((x (car args))
	(y (cadr args)))
    (when (not (and (numberp x) (numberp y)))
      (princ "The Move command requires 2 numbers as args")
      (return-from exec-move-com nil))
    (move-game game x y)))

(defun eval-play-command (game com-list)
  (case (car com-list)
    (print (print-game game) nil)
    (reverse (reverse-game game))
    (move (exec-move-com game (cdr com-list)))
    (t (princ "This command is not defined.")
       nil)))
