(defun make-uniform-policy(game)
  (let* ((moves (make-moves game))
	(len (moves-len moves)))
    (mapcar-moves (lambda (move) (/ 1 len)) moves)))

(defun decide-move-by-random-policy(game fn-make-policy rand-val)
  (if (is-game-end game) (return-from decide-move-by-random-policy))
  (let* ((moves (make-moves game))
	 (policy (funcall fn-make-policy game)))
    (labels ((decide (count sum rest-policy)
	       (cond ((null (car rest-policy)) count)
		     ((>= sum rand-val) count)
		     (t (decide (+ count 1) (+ sum (car rest-policy))
				(cdr rest-policy))))))
      (get-nth-move moves (decide 0 (car policy) (cdr policy))))))
	     
(defun move-by-random-policy (game fn-make-policy)
  (let ((move (decide-move-by-random-policy game fn-make-policy (random 1.0) )))
    (move-game game (car move) (cdr move))))
